[package]
name = "prod-server"
version = "0.1.0"
edition = "2021"

[dependencies]
core-server = { path = "../core/" }
mime_guess = "2.0"
rust-embed = { version = "8.4", features = ["interpolate-folder-path"] }

[lints]
workspace = true
