[package]
name = "dev-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12"
core-server = { path = "../core/" }
webbrowser = "1.0"

[build-dependencies]
anyhow = "1.0"
dotenvy = "0.15"


[lints]
workspace = true
