[package]
name = "dev-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12"
core-server = { path = "../core/" }
listenfd = "1.0"
webbrowser = "1.0"

[build-dependencies]
anyhow = "1.0"
toml = "0.8"


[lints]
workspace = true
