[package]
name = "server-core"
version = "0.0.0"
edition = "2021"

[dependencies]
# Axum Server Deps ------------------------------------------------------------
anyhow = "1.0"
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
anyhow = "1.0"
dotenvy = "0.15"

[lints]
workspace = true
