[package]
name = "patras"
version = "0.1.0"
edition = "2021"

[dependencies]
prod-server = { path = "../prod/" }
shuttle-axum = "0.46.0"
shuttle-runtime = "0.46.0"
shuttle-shared-db = { version = "0.46.0", features = ["postgres"] }

[lints]
workspace = true
