[package]
name = "persist"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api/" }
derivative = "2.2"
dotenvy = "0.15"
thiserror = "1.0"
# DB
deadpool-postgres = "0.14"
tokio-postgres = "0.7"

[lints]
workspace = true
